### ISSUE TITLE
Font bold is broken

### ISSUE THREAD

**Issue by pasnox** [fralx/LimeReport#118]
The property editor is correctly updating the property but the font does not change.
I tried 8 differents fonts, all don't change when checking bold property on a Text item.

**Comment by fralx** [comment]
Hi. I can't reproduce the problem. 
What branch do you use?

**Comment by pasnox** [comment]
Master on macos Qt 5.11 and 5.9.4

**Comment by fralx** [comment]
I've checked. It works for me. How it looks for you? 

![screen shot 2018-07-05 at 21 24 23](https://user-images.githubusercontent.com/14914730/42340940-150de764-809a-11e8-9f66-74dbba0d5b62.png)
![screen shot 2018-07-05 at 21 25 00](https://user-images.githubusercontent.com/14914730/42340945-17620644-809a-11e8-8f98-a16551f32ba4.png)

**Comment by pasnox** [comment]
I'm using Qt 5.9.6 now, and LimeReport master (1.4.80) on macOS High Sierra.
I still have the problem, but now that I did checked with the same family than you (Al Bayan), it works.
So it seems the problem only appear with some family, like in my case Arial, Courrier, Courrier New.
Looks like a Qt issue (or maybe the weight appleid to the font is not big enough depending the used family)

**Comment by fralx** [comment]
It`s very strange. I have test it on High Sierra and have the next result.  
For Qt 5.6.2
![screen shot 2018-07-10 at 16 25 13](https://user-images.githubusercontent.com/14914730/42512898-608ac35c-845e-11e8-8d16-441e806be883.png)
![screen shot 2018-07-10 at 16 23 14](https://user-images.githubusercontent.com/14914730/42512868-507b7f42-845e-11e8-8bed-123fd997bcf5.png)
For Qt 5.11
![screen shot 2018-07-10 at 16 38 29](https://user-images.githubusercontent.com/14914730/42513592-ffae31f2-845f-11e8-8fe0-17a2b5dc0e21.png)
![screen shot 2018-07-10 at 16 38 53](https://user-images.githubusercontent.com/14914730/42513595-03969c0a-8460-11e8-8fd0-946114f771e3.png)

**Comment by pasnox** [comment]
Can you make screenshots for bold/non bold with Arial on 5.9.6 ?

**Comment by fralx** [comment]
It'll take a while, I'll do it later.

**Comment by fralx** [comment]
Got it.
5.9.6
![screen shot 2018-07-10 at 17 05 21](https://user-images.githubusercontent.com/14914730/42515107-a83f65a4-8463-11e8-9e20-34206599ceb7.png)
![screen shot 2018-07-10 at 17 06 13](https://user-images.githubusercontent.com/14914730/42515108-a8b73822-8463-11e8-977f-eeed976b0a3b.png)

**Comment by pasnox** [comment]
And can you post the bolded versus unbolded screenshot for Arial by
example? Also I noticed weird behavior when using the native font dialog
then editing specific items from the property editor, properties were not
reflecting, by example the family was not changing

**Comment by fralx** [comment]
Ah, I think I understand what's going on. I select font by font editor in toolbar and you select in object inspector through font editor. It seems the bug is there. I will check it.
My screens :
![screen shot 2018-07-10 at 21 28 23](https://user-images.githubusercontent.com/14914730/42530269-6b45c870-8489-11e8-82f4-50a2800a5b2d.png)
![screen shot 2018-07-10 at 21 28 42](https://user-images.githubusercontent.com/14914730/42530272-6e6c0280-8489-11e8-9b96-6f2d0e5d6351.png)

**Comment by pasnox** [comment]
Ah indeed, I should have specified that early 😉

**Comment by fralx** [comment]
I have fixed the error. Check it please.

**Comment by pasnox** [comment]
So, for a new dropped text item it worked fine.
But this does not fix my issue.
After more testing I found the origin - the native OSX font dialog.
It looks like using the native font dialog fill the QFont with the stylename, like 'Regular', 'Bold' etc and this is persisted in the xml files.
This property is then never editable again in the LimeReport UI, we can only select a font from the Font combobox.
The UI only propose to edit italic, bold, underline, size and family.
So if in the native font dialog we choose a "typeface" this then start to make uncontrollable things in the UI because the typeface is not expected to be used.
Please remove serialization / deserialization of such property so that the default is use, and let Qt control the typeface on its own from the italic/underline/bold QFont properties.

**Comment by pasnox** [comment]
Yep - fix my issues 👍 
Thank you for your patience ;)

**Comment by fralx** [comment]
You are welcome :)
