### ISSUE TITLE
Can add a lock property for all items?

### ISSUE THREAD

**Issue by liufeijin** [fralx/LimeReport#208]
add a property for items, avoid to change or move the position of a ready items when adjust some item.
  Because it's position is easy changed when i click a ready item by mouse.

**Comment by fralx** [comment]
Ok, I will think about it

**Comment by liufeijin** [comment]
great news !
Thanks!

**Comment by fralx** [comment]
Hi!
I have added the geometryLock property to report items. From now you can select items and press Ctrl+L to lock items and Ctrl+Shift+L to unlock items. Right mouse button and direct change property also work for this task.

**Comment by liufeijin** [comment]
I have tried it is ok.
thank you very much! It is a great function.

**Comment by liufeijin** [comment]
There is a bug  that if the position of item is located by align tool button after locked the item can be moved 1 time. 
I think may be lock property will not effect if the position is fit by align tool button.
cloud you have a check?
![555](https://user-images.githubusercontent.com/19425403/60378876-1fa3ad80-9a5c-11e9-8c20-847a74498eb7.png)

**Comment by fralx** [comment]
Hi!
I have fixed the problem. You can check it.

**Comment by liufeijin** [comment]
Hi fralx
The bug is still , i made a movie for your reference.

[lock.zip](https://github.com/fralx/LimeReport/files/3342490/lock.zip)

**Comment by fralx** [comment]
Hi! 
Yet another try :)   
Check it, please.

**Comment by liufeijin** [comment]
Great!
Now, it is ok!
Thank you very much!
